version: "3.7"

services:
  index_service:
    image: index
    container_name: index
    ports:
      - "3000:3000"
    restart: always
    init: true
  score_service:
    image: score
    container_name: score
    ports:
      - "3001:3001"
    restart: always
    init: true
