version: "3.7"

services:
  auth_service:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "2999:2999"
    restart: always
    init: true

  main_service:
    build:
      context: ./main
    container_name: main
    ports:
      - "3000:3000"
    restart: always
    init: true

  score_service:
    build:
      context: ./score
    container_name: score
    ports:
      - "3001:3001"
    restart: always
    init: true

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - monitor-net

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks:
      - monitor-net

networks:
  monitor-net:
