version: "3.7"

services:
  auth_service:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "2999:2999"
    restart: always
    init: true

  main_service:
    build:
      context: ./main
    container_name: main
    ports:
      - "3000:3000"
    restart: always
    init: true

  score_service:
    build:
      context: ./score
    container_name: score
    ports:
      - "3001:3001"
    restart: always
    init: true
