version: "3.9"

services:
  index_service:
    image: index
    container_name: index
    ports:
      - "3000:3000"
    restart: always
    init: true
  score-db_service:
    image: score_db
    container_name: score_db
    ports:
      - "3001:3001"
    restart: always
    init: true
