version: "3.7"

services:
  index_service:
    image: main
    container_name: main
    ports:
      - "3000:3000"
    restart: always
    init: true
  db_service:
    image: db
    container_name: db
    ports:
      - "3001:3001"
    restart: always
    init: true
