version: "3.7"

services:
  auth_service:
    image: auth
    container_name: auth
    ports:
      - "2999:2999"
    restart: always
    init: true
  main_service:
    image: main
    container_name: main
    ports:
      - "3000:3000"
    restart: always
    init: true
  db_service:
    image: db
    container_name: db
    ports:
      - "3001:3001"
    restart: always
    init: true
